version: '3.8'

services:
  postgres_dev:
    image: postgres:15-alpine
    container_name: auth_backend_db_dev
    environment:
      POSTGRES_USER: c_log
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: auth_backend_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
  postgres_test:
    image: postgres:15-alpine
    container_name: auth_backend_db_test
    environment:
      POSTGRES_USER: c_log
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: auth_backend_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_dev:
  pgdata_test:
